var builder = WebApplication.CreateBuilder(args);

// Generated by CoPilot
// Add services to the container and enable controllers
builder.Services.AddControllers();

var app = builder.Build();

// Map controllers using minimal hosting model best practice
app.MapControllers();

app.Run();
