using Microsoft.AspNetCore.Mvc;

namespace web.Controllers
{
    /// <summary>
    /// Controller to handle greeting requests.
    /// Generated by CoPilot
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public class GreetController : ControllerBase
    {
        /// <summary>
        /// Greets the user by username.
        /// Generated by CoPilot
        /// </summary>
        /// <param name="username">The username to greet.</param>
        /// <returns>A greeting message.</returns>
        [HttpGet]
        public IActionResult Get([FromQuery] string username)
        {
            if (string.IsNullOrWhiteSpace(username))
            {
                return BadRequest("Username is required.");
            }
            var message = $"Hello, {username}! Welcome to the .NET Core API.";
            return Ok(new { greeting = message });
        }
    }
}
